/* ═════════════════════════════════════
   AIOS-X · Export & Print Center
   PDF · Markdown · JSON · CSV · HTML
═════════════════════════════════════ */
'use strict';

// ── SESSION STORE ──
// All logs and outputs are accumulated here for export
const SessionStore = {
  orchestrationLogs: [],
  debateTranscripts: [],
  executionLogs: [],
  securityLogs: [],
  memoryNodes: [],
  pipelineSteps: [],
  modelTestResults: [],
  metadata: {
    sessionStart: new Date().toISOString(),
    version: 'AIOS-X v2.0',
    models: [],
  },
};

function recordLog(category, entry) {
  if (SessionStore[category]) SessionStore[category].push({ ...entry, ts: new Date().toISOString() });
}

// ── MAIN EXPORT ACTION ──
function exportAction(type) {
  const scope = document.querySelector('input[name="exportScope"]:checked')?.value || 'current';
  closeModal('exportModal');

  switch (type) {
    case 'print':   exportPrint(); break;
    case 'markdown': exportMarkdown(scope); break;
    case 'json':    exportJSON(scope); break;
    case 'csv':     exportCSV(); break;
    case 'html':    exportHTML(scope); break;
    case 'clipboard': exportClipboard(scope); break;
  }
}

// ── PRINT / PDF ──
function exportPrint() {
  injectPrintHeader();
  window.print();
  showToast('Print dialog opened', 'info');
}

function injectPrintHeader() {
  const art = document.getElementById('printArtifact');
  if (!art) return;
  art.innerHTML = `
    <div class="print-header">AIOS-X — Agentic Intelligence Orchestration System</div>
    <div class="print-meta">
      Generated: ${new Date().toLocaleString()} | Session: ${SessionStore.metadata.sessionStart}<br>
      Models used: ${SessionStore.metadata.models.join(', ') || 'None'}<br>
      March 2026 AI Landscape Integration Report
    </div>
  `;
}

// ── MARKDOWN REPORT ──
function exportMarkdown(scope) {
  const now = new Date();
  const lines = [
    `# AIOS-X Session Report`,
    `**Generated:** ${now.toLocaleString()}`,
    `**Session Start:** ${SessionStore.metadata.sessionStart}`,
    `**Version:** ${SessionStore.metadata.version}`,
    '',
    '---',
    '',
  ];

  if (scope === 'current' || scope === 'all') {
    const activeTab = document.querySelector('.tab-panel.active');
    if (activeTab) {
      const tabId = activeTab.id.replace('tab-', '');
      lines.push(`## ${getTabTitle(tabId)}`);
      lines.push('');

      // Extract log content
      const logBody = activeTab.querySelector('.log-body');
      if (logBody && logBody.children.length > 0) {
        lines.push('### Log Entries');
        lines.push('```');
        Array.from(logBody.children).forEach(entry => {
          lines.push(entry.innerText || entry.textContent);
        });
        lines.push('```');
        lines.push('');
      }

      // Extract visible text cards
      activeTab.querySelectorAll('.card').forEach(card => {
        const title = card.querySelector('.card-title')?.textContent?.trim();
        if (title) {
          lines.push(`### ${title}`);
          lines.push('');
        }
      });
    }
  }

  if (scope === 'session' || scope === 'all') {
    if (SessionStore.orchestrationLogs.length > 0) {
      lines.push('## Orchestration Log');
      SessionStore.orchestrationLogs.forEach(l => lines.push(`- [${l.ts}] ${l.msg}`));
      lines.push('');
    }

    if (SessionStore.debateTranscripts.length > 0) {
      lines.push('## Debate Transcripts');
      SessionStore.debateTranscripts.forEach(d => {
        lines.push(`### ${d.topic || 'Debate'}`);
        (d.messages || []).forEach(m => {
          lines.push(`**${m.model}:** ${m.text}`);
          lines.push('');
        });
      });
    }

    if (SessionStore.securityLogs.length > 0) {
      lines.push('## Security Events');
      SessionStore.securityLogs.forEach(l => lines.push(`- [${l.ts}] [${(l.level||'info').toUpperCase()}] ${l.msg}`));
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('*Generated by AIOS-X — March 2026 AI Landscape Intelligence System*');

  downloadText(lines.join('\n'), `aiosx-report-${datestamp()}.md`);
  showToast('Markdown report exported', 'success');
}

// ── JSON ARTIFACT ──
function exportJSON(scope) {
  const artifact = {
    meta: {
      ...SessionStore.metadata,
      exportedAt: new Date().toISOString(),
      scope,
    },
    orchestration: scope !== 'current' ? SessionStore.orchestrationLogs : [],
    debate: scope !== 'current' ? SessionStore.debateTranscripts : [],
    execution: scope !== 'current' ? SessionStore.executionLogs : [],
    security: scope !== 'current' ? SessionStore.securityLogs : [],
    memory: scope !== 'current' ? SessionStore.memoryNodes : [],
    modelTests: SessionStore.modelTestResults,
  };

  if (scope === 'current') {
    // Add current panel state
    const activeTab = document.querySelector('.tab-panel.active');
    if (activeTab) {
      artifact.currentPanel = {
        id: activeTab.id,
        textContent: activeTab.innerText?.slice(0, 5000),
      };
    }
  }

  downloadJSON(artifact, `aiosx-artifact-${datestamp()}.json`);
  showToast('JSON artifact exported', 'success');
}

// ── CSV DATA ──
function exportCSV() {
  const rows = [
    ['Model', 'Provider', 'MMLU', 'HumanEval', 'MATH', 'Context', 'Cost/1M In', 'Cost/1M Out', 'Tier'],
  ];

  if (typeof MODEL_REGISTRY !== 'undefined') {
    MODEL_REGISTRY.forEach(m => {
      rows.push([
        m.name, m.provider, m.mmlu, m.humanEval, m.math,
        m.context, m.inputCost, m.outputCost, m.tier,
      ]);
    });
  }

  const csv = rows.map(r => r.map(cell => `"${String(cell).replace(/"/g,'""')}"`).join(',')).join('\n');
  downloadText(csv, `aiosx-models-${datestamp()}.csv`);
  showToast('CSV exported', 'success');
}

// ── HTML SNAPSHOT ──
function exportHTML(scope) {
  const activeTab = document.querySelector('.tab-panel.active');
  const content = scope === 'all' ? document.getElementById('main')?.innerHTML || '' : activeTab?.innerHTML || '';

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>AIOS-X Snapshot — ${new Date().toLocaleString()}</title>
<style>
  body { font-family: Inter, sans-serif; background: #04050a; color: #f1f5f9; padding: 20px; }
  .card { background: #111827; border: 1px solid rgba(255,255,255,0.07); border-radius: 8px; padding: 16px; margin-bottom: 12px; }
  .card-title { font-size: 11px; font-weight: 700; text-transform: uppercase; color: #475569; margin-bottom: 10px; }
  table { width: 100%; border-collapse: collapse; }
  th, td { padding: 8px; border-bottom: 1px solid rgba(255,255,255,0.05); font-size: 12px; }
  th { color: #475569; font-size: 9px; text-transform: uppercase; }
  .log-entry { padding: 2px 6px; font-family: monospace; font-size: 11px; }
</style>
</head>
<body>
<h1 style="color:#38bdf8;margin-bottom:4px">AIOS-X Snapshot</h1>
<p style="color:#475569;font-size:11px;margin-bottom:20px">Generated: ${new Date().toLocaleString()}</p>
${content}
</body>
</html>`;

  downloadText(html, `aiosx-snapshot-${datestamp()}.html`);
  showToast('HTML snapshot exported', 'success');
}

// ── CLIPBOARD ──
function exportClipboard(scope) {
  const activeTab = document.querySelector('.tab-panel.active');
  const text = activeTab?.innerText?.slice(0, 10000) || 'No content';
  navigator.clipboard.writeText(text).then(() => {
    showToast('Copied to clipboard', 'success');
  }).catch(() => {
    showToast('Clipboard access denied', 'error');
  });
}

// ── SPECIFIC EXPORT HELPERS ──
function exportOrchestratorSession() {
  const logBody = document.getElementById('orchestrationLogBody');
  const entries = logBody ? Array.from(logBody.children).map(e => e.textContent).join('\n') : '';
  const taskInput = document.getElementById('taskInput')?.value || '';

  const content = [
    '# AIOS-X Orchestration Session',
    `Date: ${new Date().toLocaleString()}`,
    '',
    '## Task',
    taskInput,
    '',
    '## Orchestration Log',
    entries,
  ].join('\n');

  downloadText(content, `aiosx-orchestration-${datestamp()}.md`);
  showToast('Orchestration session exported', 'success');
}

function exportDebate() {
  const flow = document.getElementById('debateFlow');
  const synthesis = document.getElementById('synthesisContent');
  const topic = document.getElementById('debateTopic')?.value || 'unknown';

  const lines = [`# AIOS-X Debate Transcript`, `Topic: ${topic}`, `Date: ${new Date().toLocaleString()}`, ''];

  if (flow) {
    Array.from(flow.children).forEach(el => {
      const model = el.querySelector('.dm-model')?.textContent || '';
      const text = el.querySelector('.dm-text')?.textContent || '';
      if (model) lines.push(`**${model}:** ${text}`, '');
    });
  }

  if (synthesis?.textContent) {
    lines.push('## Synthesis', synthesis.textContent);
  }

  downloadText(lines.join('\n'), `aiosx-debate-${datestamp()}.md`);
  showToast('Debate transcript exported', 'success');
}

function exportPipeline() {
  const steps = document.getElementById('pipelineSteps');
  const log = document.getElementById('execLogBody');
  const stepsText = steps ? Array.from(steps.children).map((s,i) => {
    const name = s.querySelector('.step-name')?.textContent || '';
    const agent = s.querySelector('.step-agent')?.textContent || '';
    const status = s.querySelector('.step-status')?.textContent || '';
    return `${i+1}. ${name} [${agent}] — ${status}`;
  }).join('\n') : '';

  const content = [`# AIOS-X Pipeline Export`, `Date: ${new Date().toLocaleString()}`, '', '## Steps', stepsText,
    '', '## Execution Log', log ? Array.from(log.children).map(e => e.textContent).join('\n') : ''].join('\n');

  downloadText(content, `aiosx-pipeline-${datestamp()}.md`);
  showToast('Pipeline exported', 'success');
}

function exportMemory() {
  const nodes = typeof getMemoryNodes === 'function' ? getMemoryNodes() : [];
  downloadJSON({ nodes, exportedAt: new Date().toISOString() }, `aiosx-memory-${datestamp()}.brv.json`);
  showToast('Memory exported as .brv.json', 'success');
}

function exportSecReport() {
  const log = document.getElementById('secLogBody');
  const threats = document.getElementById('threatGrid');
  const content = [
    '# AIOS-X Security Report',
    `Date: ${new Date().toLocaleString()}`,
    '',
    '## Threat Summary',
    threats ? threats.innerText : '',
    '',
    '## Security Events',
    log ? Array.from(log.children).map(e => e.textContent).join('\n') : '',
  ].join('\n');
  downloadText(content, `aiosx-security-report-${datestamp()}.md`);
  showToast('Security report exported', 'success');
}

// ── HELPERS ──
function datestamp() {
  return new Date().toISOString().slice(0, 16).replace(/[T:]/g, '-');
}

function getTabTitle(tabId) {
  const titles = {
    orchestrator: '⬡ Orchestrator',
    models: '🤖 Multi-Model Registry',
    debate: '💬 Debate Arena',
    memory: '🧠 Memory Layer',
    execution: '⚡ Execution Pipeline',
    market: '📊 Market Intelligence',
    security: '🛡️ Security & Compliance',
  };
  return titles[tabId] || tabId;
}

// Expose
window.exportAction = exportAction;
window.exportPrint = exportPrint;
window.exportOrchestratorSession = exportOrchestratorSession;
window.exportDebate = exportDebate;
window.exportPipeline = exportPipeline;
window.exportMemory = exportMemory;
window.exportSecReport = exportSecReport;
window.SessionStore = SessionStore;
window.recordLog = recordLog;
